# Generated by Django 4.2.6 on 2024-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_remove_sales_user_profile_sales_state_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank='True', choices=[('wellness', 'Wellness'), ('beauty', 'Beauty')], default='wellness', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='subcategory',
            field=models.CharField(blank='True', choices=[('covid_essential', 'COVID Essential'), ('diabetic_support', 'Diabetic Support'), ('eye_wear', 'Eye Wear'), ('hair_care', 'Hair Care'), ('skin_care', 'Skin Care'), ('mens_grooming', "Men's Grooming")], max_length=20),
        ),
    ]
