# Generated by Django 4.2.6 on 2024-02-21 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exam', '0008_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_epf_wages', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_esi_wages', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rest_allow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_epf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_esi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_epf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_esi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
