# Generated by Django 4.2.6 on 2024-03-12 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0014_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
