# Generated by Django 4.2.6 on 2024-03-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0016_orderplaceaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaceaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderplaceaddress',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderplaceaddress',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orderplaceaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orderplaceaddress',
            name='zipcode',
        ),
    ]
