# Generated by Django 4.2.6 on 2024-03-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0017_remove_orderplaceaddress_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_applied', models.BooleanField(default=False)),
                ('coupon_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
