# Generated by Django 4.2.6 on 2024-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0019_address_delete_orderplaceaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
