# Generated by Django 4.2.6 on 2024-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0023_rename_amount_payment_total_amount_payment_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentamount',
            name='shipping_charges',
            field=models.TextField(),
        ),
    ]
