# Generated by Django 4.2.6 on 2024-03-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0024_alter_paymentamount_shipping_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentamount',
            old_name='shipping_charges',
            new_name='shipping_charge',
        ),
    ]
