# Generated by Django 4.2.6 on 2024-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0025_rename_shipping_charges_paymentamount_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentamount',
            name='mrp_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
