# Generated by Django 4.2.6 on 2024-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0027_alter_paymentamount_additional_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentamount',
            name='shipping_charge',
            field=models.TextField(null=True),
        ),
    ]
