# Generated by Django 4.2.6 on 2024-03-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0028_alter_paymentamount_shipping_charge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentAmount',
        ),
    ]
